opencodeiiita/CLI-For-You

- My-RPG/src/game-engine/index.js
Issue: #13
made explore , use <item> , drop <item>
> Chat gpt does not help

- QR-Encoder-Decoder/Rndastech/commands.txt
- QR-Encoder-Decoder/Rndastech/encode.py
- QR-Encoder-Decoder/Rndastech/requirements.txt
Issue: #5 
- Developed a Python script (encode.py) to generate QR codes from text files.
- Implemented error handling for non-existent files, empty files, and unexpected exceptions, ensuring graceful execution.
- Output QR code image file.
- Example usage instructions: python encode.py encode <input_file> <output_image>.
- Generates QR with file extension followed by file contents to allow for easy encryption/decryption of every file type (txt, png, mp3...)
> QR Code Encode in Python

- QR-Encoder-Decoder/Rachit/commands.txt
- QR-Encoder-Decoder/Rachit/qr.py
- QR-Encoder-Decoder/Rachit/requirements.txt
Issue : #5 
Description : Created qr.py,requirements.txt and commands.txt for saving file's data in a qr code.
Input/Output SS :
> Created qr.py,requirements.txt and commands.txt for saving file's data in a qr code

- QR-Encoder-Decoder/Puravi/commands.txt
- QR-Encoder-Decoder/Puravi/qr.py
- QR-Encoder-Decoder/Puravi/requirements.txt
Issue: #5 
Created qr_encoder in python, attached screenshots
> Added QR-encoder, requirements.txt and commands.txt

- QR-Encoder-Decoder/Ashutosh/command.txt
- QR-Encoder-Decoder/Ashutosh/qr.py
- QR-Encoder-Decoder/Ashutosh/requirements.txt
Issue: #5
Created qr_encoder in python, attached screenshots
> QR Encoder addded

- QR-Encoder-Decoder/Sarvesh0955/code.py
- QR-Encoder-Decoder/Sarvesh0955/commands.txt
- QR-Encoder-Decoder/Sarvesh0955/requirment.txt
Issue: #5  
QR encoder python
to run use command:
python code.py <input_file_path> <output_qr_image_path>
> QR encoder python

- QR-Encoder-Decoder/Lokesh11868/code.js
- QR-Encoder-Decoder/Lokesh11868/commands.txt
- QR-Encoder-Decoder/Lokesh11868/requirements.txt
issue: #5
Developed a QR code encoder decoder using Node.js and JavaScript:  
supports text, image, audio, pdf.
1. **Directory Structure**: Created a directory.  
2. **Core Functionality**: Implemented `code.js` to handle QR code encoding and decoding.  
3. **Documentation**: Added a `requirements.txt` file to specify dependencies and a `commands.txt` file to provide setup and usage instructions.
>  Added QR Code Encoder

- QR-Encoder-Decoder/apexcoder007/commands.txt
- QR-Encoder-Decoder/apexcoder007/qr_encoder.py
- QR-Encoder-Decoder/apexcoder007/requirements.txt
Issue : #5 
1) created py_encoder.py file
2) added the dependencies in the requirements.txt file
3) added the commands to run in the commands.txt file
screenshots:
> added qr_encoder.py

- My-RPG/package.json
- My-RPG/src/game-engine/combat.js
- My-RPG/src/game-engine/enemy.js
- My-RPG/src/game-engine/index.js
Issue: #41
Added everything as mentioned in issue
> combat is real

- My-RPG/Story/Veil of Eternity.txt
Issue: #26 
Added story in text file.
> Story added

- My-RPG/Story/Story-1-HGRgamer.txt
Issue: #26 
Wrote a short intro story line
> Intro Story-line (Issue 3rd)

- My-RPG/Story/My-Story.txt
Issue: #26 
Added My-Story.txt
> Created My-Story.txt

- My-RPG/Story/iit2023028.txt
Issue : #26
added iit2023028.txt
> Storyline 1

- My-RPG/Story/Story1.txt
ISSUE: #26 
Added Story1
You have mentioned that I didnt add the story there in the story.txt in my prev PR. Kindly check now , Hope it's correct now.Thank you..
> Created Story1.txt

- QR-Encoder-Decoder/saipy10/QREncoderCloud.txt
Issue: #79 
Gave suggestions based on my genuine knowledge and expertise about how to handle the given problem of QR Encoder for big big without hampering the performance of the systems,
> QR Encoder Linked with Cloud Storage Platform

- QR-Encoder-Decoder/Darkknight0125/Cloud_suggestion.txt
Issue: #79 
Gave a suggestion based on personal experience, feel free to utilise anything you feel valuable.
> Cloud suggestion

- QR-Encoder-Decoder/Ashutosh/official-ashutosh.txt
> Added My research

- QR-Encoder-Decoder/shrut2606/qr-encoder.txt
Issue: #79 
QR large files problem solved
> Large files in QR

- My-RPG/src/game-engine/combatNew.js
issue:#90
added progress bar which resets after every combat round and added colour change feature
> added progress bar (resolved the double letter display issue)

- TexToImage/src/final.js
Issue: #99 
Added final.js file
> User input and interface for TexToImage tool
